"""add_notifications_bot_users_and_booking_fields

Revision ID: c926e65d5b7e
Revises: 887a31edf9cf
Create Date: 2026-01-29 16:07:47.090327

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c926e65d5b7e"
down_revision: Union[str, None] = "887a31edf9cf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bot_users",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("bot_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk__bot_users__user_id__users")
        ),
        sa.PrimaryKeyConstraint("user_id", "bot_id", name=op.f("pk__bot_users")),
    )
    op.alter_column(
        "notifications",
        "type",
        existing_type=sa.VARCHAR(length=20),
        comment="Тип уведомления",
        existing_nullable=False,
    )
    op.alter_column(
        "notifications",
        "status",
        existing_type=sa.VARCHAR(length=20),
        comment="Статус уведомления",
        existing_nullable=False,
        existing_server_default=sa.text("'pending'::character varying"),
    )
    op.alter_column(
        "notifications",
        "booking_id",
        existing_type=sa.INTEGER(),
        comment="ID бронирования",
        existing_nullable=False,
    )
    op.alter_column(
        "notifications",
        "user_id",
        existing_type=sa.UUID(),
        comment="ID пользователя",
        existing_nullable=False,
    )
    op.alter_column(
        "notifications",
        "scheduled_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Время запланированной отправки",
        existing_nullable=False,
    )
    op.alter_column(
        "notifications",
        "processed_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Время фактической отправки",
        existing_nullable=True,
    )
    op.alter_column(
        "notifications",
        "message",
        existing_type=sa.TEXT(),
        comment="Текст отправленного сообщения",
        existing_nullable=True,
    )
    op.alter_column(
        "notifications",
        "error",
        existing_type=sa.TEXT(),
        comment="Ошибка при отправке",
        existing_nullable=True,
    )
    op.alter_column(
        "notifications",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "notifications",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(
        op.f("ix__notifications__status_scheduled"), table_name="notifications"
    )
    op.drop_index(op.f("ix__notifications__type_scheduled"), table_name="notifications")
    op.drop_index(op.f("ix__notifications__user_status"), table_name="notifications")
    op.add_column("resources", sa.Column("description", sa.Text(), nullable=True))
    op.add_column(
        "resources",
        sa.Column(
            "resource_type",
            sa.Enum("квартира", "дом", "студия", "офис", name="resource_type"),
            nullable=True,
        ),
    )
    op.add_column(
        "resources", sa.Column("location", sa.VARCHAR(length=255), nullable=True)
    )
    op.add_column("resources", sa.Column("price_per_hour", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("resources", "price_per_hour")
    op.drop_column("resources", "location")
    op.drop_column("resources", "resource_type")
    op.drop_column("resources", "description")
    op.create_index(
        op.f("ix__notifications__user_status"),
        "notifications",
        ["user_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix__notifications__type_scheduled"),
        "notifications",
        ["type", "scheduled_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix__notifications__status_scheduled"),
        "notifications",
        ["status", "scheduled_at"],
        unique=False,
    )
    op.alter_column(
        "notifications",
        "updated_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "notifications",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "notifications",
        "error",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="Ошибка при отправке",
        existing_nullable=True,
    )
    op.alter_column(
        "notifications",
        "message",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="Текст отправленного сообщения",
        existing_nullable=True,
    )
    op.alter_column(
        "notifications",
        "processed_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Время фактической отправки",
        existing_nullable=True,
    )
    op.alter_column(
        "notifications",
        "scheduled_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Время запланированной отправки",
        existing_nullable=False,
    )
    op.alter_column(
        "notifications",
        "user_id",
        existing_type=sa.UUID(),
        comment=None,
        existing_comment="ID пользователя",
        existing_nullable=False,
    )
    op.alter_column(
        "notifications",
        "booking_id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="ID бронирования",
        existing_nullable=False,
    )
    op.alter_column(
        "notifications",
        "status",
        existing_type=sa.VARCHAR(length=20),
        comment=None,
        existing_comment="Статус уведомления",
        existing_nullable=False,
        existing_server_default=sa.text("'pending'::character varying"),
    )
    op.alter_column(
        "notifications",
        "type",
        existing_type=sa.VARCHAR(length=20),
        comment=None,
        existing_comment="Тип уведомления",
        existing_nullable=False,
    )
    op.drop_table("bot_users")
    # ### end Alembic commands ###
