"""new fields 'available_date/start/end'

Revision ID: eed720e384e3
Revises: 3f8aaed4c594
Create Date: 2026-01-30 19:19:13.831942

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "eed720e384e3"
down_revision: Union[str, None] = "3f8aaed4c594"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "resources",
        sa.Column("available_date", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "resources",
        sa.Column("available_start", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "resources",
        sa.Column("available_end", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("resources", "available_end")
    op.drop_column("resources", "available_start")
    op.drop_column("resources", "available_date")
    # ### end Alembic commands ###
