"""add_description

Revision ID: a404b67a6135
Revises: c926e65d5b7e
Create Date: 2026-01-29 20:04:10.510420

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a404b67a6135"
down_revision: Union[str, None] = "c926e65d5b7e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "type", sa.String(length=20), nullable=False, comment="Тип уведомления"
        ),
        sa.Column(
            "status", sa.String(length=20), nullable=False, comment="Статус уведомления"
        ),
        sa.Column(
            "booking_id", sa.Integer(), nullable=False, comment="ID бронирования"
        ),
        sa.Column("user_id", sa.UUID(), nullable=False, comment="ID пользователя"),
        sa.Column(
            "scheduled_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Время запланированной отправки",
        ),
        sa.Column(
            "processed_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Время фактической отправки",
        ),
        sa.Column(
            "message", sa.Text(), nullable=True, comment="Текст отправленного сообщения"
        ),
        sa.Column("error", sa.Text(), nullable=True, comment="Ошибка при отправке"),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["bookings.id"],
            name=op.f("fk__notifications__booking_id__bookings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk__notifications__user_id__users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__notifications")),
    )
    op.create_index(
        op.f("ix__notifications__booking_id"),
        "notifications",
        ["booking_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix__notifications__id"), "notifications", ["id"], unique=False
    )
    op.create_index(
        op.f("ix__notifications__scheduled_at"),
        "notifications",
        ["scheduled_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix__notifications__status"), "notifications", ["status"], unique=False
    )
    op.create_index(
        op.f("ix__notifications__type"), "notifications", ["type"], unique=False
    )
    op.create_index(
        op.f("ix__notifications__user_id"), "notifications", ["user_id"], unique=False
    )
    op.drop_column("bookings", "booking_type")
    op.drop_column("bookings", "location")
    op.drop_column("bookings", "description")
    op.add_column("resources", sa.Column("description", sa.Text(), nullable=True))
    op.add_column(
        "resources",
        sa.Column(
            "resource_type",
            sa.Enum("квартира", "дом", "студия", "офис", name="resource_type"),
            nullable=True,
        ),
    )
    op.add_column(
        "resources", sa.Column("location", sa.VARCHAR(length=255), nullable=True)
    )
    op.add_column("resources", sa.Column("price_per_hour", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("resources", "price_per_hour")
    op.drop_column("resources", "location")
    op.drop_column("resources", "resource_type")
    op.drop_column("resources", "description")
    op.add_column(
        "bookings",
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "bookings",
        sa.Column(
            "location", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "bookings",
        sa.Column(
            "booking_type",
            postgresql.ENUM("квартира", "дом", "студия", "офис", name="booking_type"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_index(op.f("ix__notifications__user_id"), table_name="notifications")
    op.drop_index(op.f("ix__notifications__type"), table_name="notifications")
    op.drop_index(op.f("ix__notifications__status"), table_name="notifications")
    op.drop_index(op.f("ix__notifications__scheduled_at"), table_name="notifications")
    op.drop_index(op.f("ix__notifications__id"), table_name="notifications")
    op.drop_index(op.f("ix__notifications__booking_id"), table_name="notifications")
    op.drop_table("notifications")
    # ### end Alembic commands ###
