# app/infrastructure/database/alembic/versions/2026_01_22_1200-notifications_table.py
"""Create notifications table

Revision ID: notifications001
Revises: a4ed92b554b0
Create Date: 2026-01-22 12:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "notifications001"
down_revision: Union[str, None] = "a4ed92b554b0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.String(20),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.String(20),
            nullable=False,
            server_default="pending",
        ),
        sa.Column("booking_id", sa.Integer(), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "scheduled_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "processed_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",  # ✅ Добавлено поле updated_at
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            onupdate=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["bookings.id"],
            name=op.f("fk__notifications__booking_id__bookings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk__notifications__user_id__users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__notifications")),
    )

    # Создаем индексы
    op.create_index(
        op.f("ix__notifications__id"),
        "notifications",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix__notifications__type"),
        "notifications",
        ["type"],
        unique=False,
    )
    op.create_index(
        op.f("ix__notifications__status"),
        "notifications",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix__notifications__booking_id"),
        "notifications",
        ["booking_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix__notifications__user_id"),
        "notifications",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix__notifications__scheduled_at"),
        "notifications",
        ["scheduled_at"],
        unique=False,
    )

    # Комбинированные индексы для производительности
    op.create_index(
        "ix__notifications__status_scheduled",
        "notifications",
        ["status", "scheduled_at"],
        unique=False,
    )
    op.create_index(
        "ix__notifications__user_status",
        "notifications",
        ["user_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix__notifications__type_scheduled",
        "notifications",
        ["type", "scheduled_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Удаляем индексы в правильном порядке
    op.drop_index("ix__notifications__type_scheduled", table_name="notifications")
    op.drop_index("ix__notifications__user_status", table_name="notifications")
    op.drop_index("ix__notifications__status_scheduled", table_name="notifications")

    op.drop_index(
        op.f("ix__notifications__scheduled_at"),
        table_name="notifications",
    )
    op.drop_index(
        op.f("ix__notifications__user_id"),
        table_name="notifications",
    )
    op.drop_index(
        op.f("ix__notifications__booking_id"),
        table_name="notifications",
    )
    op.drop_index(
        op.f("ix__notifications__status"),
        table_name="notifications",
    )
    op.drop_index(
        op.f("ix__notifications__type"),
        table_name="notifications",
    )
    op.drop_index(
        op.f("ix__notifications__id"),
        table_name="notifications",
    )

    op.drop_table("notifications")
    # ### end Alembic commands ###
