"""Initial initialization

Revision ID: 3f8aaed4c594
Revises:
Create Date: 2026-01-30 01:22:20.655353

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3f8aaed4c594"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("tlg_id", sa.BigInteger(), nullable=True),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("language_code", sa.String(), nullable=True),
        sa.Column(
            "api_token", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__users")),
        sa.UniqueConstraint("tlg_id", name=op.f("uq__users__tlg_id")),
    )
    op.create_table(
        "bot_users",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("bot_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk__bot_users__user_id__users")
        ),
        sa.PrimaryKeyConstraint("user_id", "bot_id", name=op.f("pk__bot_users")),
    )
    op.create_table(
        "customers",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("name", sa.VARCHAR(length=50), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk__customers__owner_id__users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__customers")),
    )
    op.create_table(
        "bot_configs",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column(
            "settings",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["customers.id"],
            name=op.f("fk__bot_configs__owner_id__customers"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__bot_configs")),
        sa.UniqueConstraint("owner_id", name=op.f("uq__bot_configs__owner_id")),
        sa.UniqueConstraint("token", name=op.f("uq__bot_configs__token")),
        sa.UniqueConstraint("username", name=op.f("uq__bot_configs__username")),
    )
    op.create_table(
        "customer_admins",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk__customer_admins__customer_id__customers"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk__customer_admins__user_id__users")
        ),
        sa.PrimaryKeyConstraint(
            "user_id", "customer_id", name=op.f("pk__customer_admins")
        ),
    )
    op.create_table(
        "customer_members",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk__customer_members__customer_id__customers"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk__customer_members__user_id__users")
        ),
        sa.PrimaryKeyConstraint(
            "user_id", "customer_id", name=op.f("pk__customer_members")
        ),
    )
    op.create_table(
        "resources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=255), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "resource_type",
            sa.Enum("квартира", "дом", "студия", "офис", name="resource_type"),
            nullable=True,
        ),
        sa.Column("location", sa.VARCHAR(length=255), nullable=True),
        sa.Column("price_per_hour", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk__resources__customer_id__customers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__resources")),
    )
    op.create_table(
        "bookings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("resource_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["resource_id"],
            ["resources.id"],
            name=op.f("fk__bookings__resource_id__resources"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk__bookings__user_id__users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__bookings")),
    )
    op.create_table(
        "feedbacks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("booking_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("rating", sa.SmallInteger(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint(
            "rating BETWEEN 1 AND 5", name=op.f("ck__feedbacks__rating_check")
        ),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["bookings.id"],
            name=op.f("fk__feedbacks__booking_id__bookings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk__feedbacks__customer_id__customers"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk__feedbacks__user_id__users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__feedbacks")),
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "type", sa.String(length=20), nullable=False, comment="Тип уведомления"
        ),
        sa.Column(
            "status", sa.String(length=20), nullable=False, comment="Статус уведомления"
        ),
        sa.Column(
            "booking_id", sa.Integer(), nullable=False, comment="ID бронирования"
        ),
        sa.Column("user_id", sa.UUID(), nullable=False, comment="ID пользователя"),
        sa.Column(
            "scheduled_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Время запланированной отправки",
        ),
        sa.Column(
            "processed_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Время фактической отправки",
        ),
        sa.Column(
            "message", sa.Text(), nullable=True, comment="Текст отправленного сообщения"
        ),
        sa.Column("error", sa.Text(), nullable=True, comment="Ошибка при отправке"),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["bookings.id"],
            name=op.f("fk__notifications__booking_id__bookings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk__notifications__user_id__users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__notifications")),
    )
    op.create_index(
        op.f("ix__notifications__booking_id"),
        "notifications",
        ["booking_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix__notifications__id"), "notifications", ["id"], unique=False
    )
    op.create_index(
        op.f("ix__notifications__scheduled_at"),
        "notifications",
        ["scheduled_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix__notifications__status"), "notifications", ["status"], unique=False
    )
    op.create_index(
        op.f("ix__notifications__type"), "notifications", ["type"], unique=False
    )
    op.create_index(
        op.f("ix__notifications__user_id"), "notifications", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix__notifications__user_id"), table_name="notifications")
    op.drop_index(op.f("ix__notifications__type"), table_name="notifications")
    op.drop_index(op.f("ix__notifications__status"), table_name="notifications")
    op.drop_index(op.f("ix__notifications__scheduled_at"), table_name="notifications")
    op.drop_index(op.f("ix__notifications__id"), table_name="notifications")
    op.drop_index(op.f("ix__notifications__booking_id"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_table("feedbacks")
    op.drop_table("bookings")
    op.drop_table("resources")
    op.drop_table("customer_members")
    op.drop_table("customer_admins")
    op.drop_table("bot_configs")
    op.drop_table("customers")
    op.drop_table("bot_users")
    op.drop_table("users")
    # ### end Alembic commands ###
